<details><summary style="display:list-item; font-size:16px; color:blue;">Jupyter Help</summary>
    
Having trouble testing your work? Double-check that you have followed the steps below to write, run, save, and test your code!
    
[Click here for a walkthrough GIF of the steps below](https://static-assets.codecademy.com/Courses/ds-python/jupyter-help.gif)

Run all initial cells to import libraries and datasets. Then follow these steps for each question:
    
1. Add your solution to the cell with `## YOUR SOLUTION HERE ## `.
2. Run the cell by selecting the `Run` button or the `Shift`+`Enter` keys.
3. Save your work by selecting the `Save` button, the `command`+`s` keys (Mac), or `control`+`s` keys (Windows).
4. Select the `Test Work` button at the bottom left to test your work.

![Screenshot of the buttons at the top of a Jupyter Notebook. The Run and Save buttons are highlighted](https://static-assets.codecademy.com/Paths/ds-python/jupyter-buttons.png)

Setup

In [1]:
import pandas as pd
vehicles = pd.read_csv('vehicles.csv')
vehicles.head()

,id,model,year,transmission,manufacturer,vehicle_type,fuel,fuel_configuration,best_mpge
0,12988,amg e53 4matic+ (convertible),2022,auto,mercedes-benz,sedan/wagon,hybrid electric,hybrid electric,28.0
1,689,avalanche ffv,2007,auto,chevrolet,pickup,ethanol (e85),flexible fuel,21.0
2,950,impala,2010,auto,chevrolet,sedan/wagon,ethanol (e85),flexible fuel,29.0
3,250,yukon xl ffv,2004,auto,gmc,suv,ethanol (e85),flexible fuel,18.0
4,13089,sf90 spyder,2022,auto,ferrari,sedan/wagon,plug-in hybrid electric,hybrid electric,19.0

1. Combine the comparisons `is_ethanol` and `is_methanol` to produce `True` for any row whose fuel is either ethanol or methanol. Assign the result to `combined`.

In [3]:
is_ethanol = vehicles['fuel'] == 'ethanol (e85)'
is_methanol = vehicles['fuel'] == 'methanol'
## YOUR SOLUTION HERE ##
combined = is_ethanol | is_methanol

2. Use `combined` to filter `vehicles` down to only those rows containing vehicles running on either ethanol or methanol. Assign the result to `ol_vehicles`.

In [4]:
## YOUR SOLUTION HERE ##
ol_vehicles = vehicles[combined]

# show output
ol_vehicles.head()

,id,model,year,transmission,manufacturer,vehicle_type,fuel,fuel_configuration,best_mpge
1,689,avalanche ffv,2007,auto,chevrolet,pickup,ethanol (e85),flexible fuel,21.0
2,950,impala,2010,auto,chevrolet,sedan/wagon,ethanol (e85),flexible fuel,29.0
3,250,yukon xl ffv,2004,auto,gmc,suv,ethanol (e85),flexible fuel,18.0
5,12302,silverado 4wd,2020,auto,chevrolet,pickup,ethanol (e85),flexible fuel,18.0
8,10584,sierra c / k 1500,2013,auto,gmc,pickup,ethanol (e85),flexible fuel,18.0

3. Filter `vehicles` down to only those rows with `fuel` equal to `electric` or `best_mpge` greater than `40` (the average.) Assign the result to `electric_or_above_average`.

In [6]:
## YOUR SOLUTION HERE ##
is_electric = vehicles['fuel'] == 'electric'
is_best = vehicles['best_mpge'] > 40

electric_or_above_average = vehicles[is_electric | is_best]

# show output
electric_or_above_average.head()

,id,model,year,transmission,manufacturer,vehicle_type,fuel,fuel_configuration,best_mpge
7,12875,avalon hybrid,2022,auto,toyota,sedan/wagon,hybrid electric,hybrid electric,43.0
10,10539,fortwo,2013,unknown,smart,sedan/wagon,electric,dedicated,112.0
16,11948,optima plug-in hybrid,2018,auto,kia,sedan/wagon,plug-in hybrid electric,hybrid electric,103.0
19,12035,cruze,2019,auto,chevrolet,sedan/wagon,biodiesel (b20),dedicated,48.0
21,11909,fusion hybrid fwd,2018,auto,ford,sedan/wagon,hybrid electric,hybrid electric,43.0