<details><summary style="display:list-item; font-size:16px; color:blue;">Jupyter Help</summary>
    
Having trouble testing your work? Double-check that you have followed the steps below to write, run, save, and test your code!
    
[Click here for a walkthrough GIF of the steps below](https://static-assets.codecademy.com/Courses/ds-python/jupyter-help.gif)

Run all initial cells to import libraries and datasets. Then follow these steps for each question:
    
1. Add your solution to the cell with `## YOUR SOLUTION HERE ## `.
2. Run the cell by selecting the `Run` button or the `Shift`+`Enter` keys.
3. Save your work by selecting the `Save` button, the `command`+`s` keys (Mac), or `control`+`s` keys (Windows).
4. Select the `Test Work` button at the bottom left to test your work.

![Screenshot of the buttons at the top of a Jupyter Notebook. The Run and Save buttons are highlighted](https://static-assets.codecademy.com/Paths/ds-python/jupyter-buttons.png)

Setup

In [1]:
import pandas as pd
vehicles = pd.read_csv('vehicles.csv')
vehicles.head()

,id,model,year,transmission,manufacturer,vehicle_type,fuel,fuel_configuration,best_mpge
0,12988,amg e53 4matic+ (convertible),2022,auto,mercedes-benz,sedan/wagon,hybrid electric,hybrid electric,28.0
1,689,avalanche ffv,2007,auto,chevrolet,pickup,ethanol (e85),flexible fuel,21.0
2,950,impala,2010,auto,chevrolet,sedan/wagon,ethanol (e85),flexible fuel,29.0
3,250,yukon xl ffv,2004,auto,gmc,suv,ethanol (e85),flexible fuel,18.0
4,13089,sf90 spyder,2022,auto,ferrari,sedan/wagon,plug-in hybrid electric,hybrid electric,19.0

1. The Paris agreement was a major climate change treaty enacted in `2016`. Combine the comparisons `year_gt2016` and `is_electric` to produce `True` for electric vehicles introduced after 2016. Assign the result to `combined`.

In [5]:
year_gt2016 = vehicles['year'] > 2016
is_electric = vehicles['fuel'] == 'electric'
## YOUR SOLUTION HERE ##
combined = (year_gt2016) & (is_electric)
combined

0       False
1       False
2       False
3       False
4       False
        ...
2515    False
2516    False
2517    False
2518    False
2519    False
Length: 2520, dtype: bool

2. Use `combined` to filter `vehicles` down to only those rows containing electric vehicles introduced after 2016. Assign the result to the variable `electric_and_after_2016`.

In [6]:
## YOUR SOLUTION HERE ##
electric_and_after_2016 = vehicles[combined]

# show output
electric_and_after_2016.sort_values(by='year').head()

,id,model,year,transmission,manufacturer,vehicle_type,fuel,fuel_configuration,best_mpge
916,11782,model s rwd 75 kwh,2017,auto,tesla,sedan/wagon,electric,dedicated,100.0
270,11777,model s awd - 60d,2017,auto,tesla,sedan/wagon,electric,dedicated,107.0
832,11636,i3 bev,2017,auto,bmw,sedan/wagon,electric,dedicated,137.0
829,11771,leaf,2017,auto,nissan,sedan/wagon,electric,dedicated,124.0
302,11775,model x awd - p100d,2017,auto,tesla,suv,electric,dedicated,92.0

3. Filter `vehicles` down to only thos rows corresponding to `biodiesel (b20)` fuel vehicles with `best_mpge` greater than 40 (the average). Assign the result to the variable `efficient_biodiesel`. (Note: there may not be any!)

In [16]:
## YOUR SOLUTION HERE ##

is_biodiesel = (vehicles['fuel'] == 'biodiesel (b20)')
is_above_avg = vehicles['best_mpge'] > 40
efficient_biodiesel = vehicles[is_biodiesel & is_above_avg]
# show output
efficient_biodiesel.head()

,id,model,year,transmission,manufacturer,vehicle_type,fuel,fuel_configuration,best_mpge
19,12035,cruze,2019,auto,chevrolet,sedan/wagon,biodiesel (b20),dedicated,48.0
187,11738,xe,2017,auto,jaguar,sedan/wagon,biodiesel (b20),dedicated,42.0
499,12206,xf,2019,auto,jaguar,sedan/wagon,biodiesel (b20),dedicated,42.0
501,11824,xf,2018,auto,jaguar,sedan/wagon,biodiesel (b20),dedicated,42.0
564,12036,cruze hatchback,2019,auto,chevrolet,sedan/wagon,biodiesel (b20),dedicated,45.0