<details><summary style="display:list-item; font-size:16px; color:blue;">Jupyter Help</summary>
    
Having trouble testing your work? Double-check that you have followed the steps below to write, run, save, and test your code!
    
[Click here for a walkthrough GIF of the steps below](https://static-assets.codecademy.com/Courses/ds-python/jupyter-help.gif)

Run all initial cells to import libraries and datasets. Then follow these steps for each question:
    
1. Add your solution to the cell with `## YOUR SOLUTION HERE ## `.
2. Run the cell by selecting the `Run` button or the `Shift`+`Enter` keys.
3. Save your work by selecting the `Save` button, the `command`+`s` keys (Mac), or `control`+`s` keys (Windows).
4. Select the `Test Work` button at the bottom left to test your work.

![Screenshot of the buttons at the top of a Jupyter Notebook. The Run and Save buttons are highlighted](https://static-assets.codecademy.com/Paths/ds-python/jupyter-buttons.png)

Setup

In [1]:
import pandas as pd
vehicles = pd.read_csv('vehicles.csv')
vehicles.head()

,id,model,year,transmission,manufacturer,vehicle_type,fuel,fuel_configuration,best_mpge
0,12988,amg e53 4matic+ (convertible),2022,auto,mercedes-benz,sedan/wagon,hybrid electric,hybrid electric,28.0
1,689,avalanche ffv,2007,auto,chevrolet,pickup,ethanol (e85),flexible fuel,21.0
2,950,impala,2010,auto,chevrolet,sedan/wagon,ethanol (e85),flexible fuel,29.0
3,250,yukon xl ffv,2004,auto,gmc,suv,ethanol (e85),flexible fuel,18.0
4,13089,sf90 spyder,2022,auto,ferrari,sedan/wagon,plug-in hybrid electric,hybrid electric,19.0

1. We've created a Boolean filter `is_ford_truck` that returns `True` whenever a vehicle is a Ford pickup truck. Create a new Boolean filter `not_ford_truck` that is `True` for every vehicle that is not a Ford pickup truck.

In [2]:
is_ford = vehicles['manufacturer'] == 'ford'
is_truck = vehicles['vehicle_type'] == 'pickup'
is_ford_truck = is_ford & is_truck


## YOUR SOLUTION HERE ##
not_ford_truck = ~is_ford_truck

2. Use `not_ford_truck` to filter `vehicles` to only those vehicles that aren't Ford pickup trucks. Assign the result to `not_ford_truck_vehicles`.

In [3]:
## YOUR SOLUTION HERE ##
not_ford_truck_vehicles = vehicles[not_ford_truck]

# show output
not_ford_truck_vehicles.head()

,id,model,year,transmission,manufacturer,vehicle_type,fuel,fuel_configuration,best_mpge
0,12988,amg e53 4matic+ (convertible),2022,auto,mercedes-benz,sedan/wagon,hybrid electric,hybrid electric,28.0
1,689,avalanche ffv,2007,auto,chevrolet,pickup,ethanol (e85),flexible fuel,21.0
2,950,impala,2010,auto,chevrolet,sedan/wagon,ethanol (e85),flexible fuel,29.0
3,250,yukon xl ffv,2004,auto,gmc,suv,ethanol (e85),flexible fuel,18.0
4,13089,sf90 spyder,2022,auto,ferrari,sedan/wagon,plug-in hybrid electric,hybrid electric,19.0

3. Filter `vehicles` down to only vehicles manufactured by someone **other** than `chevrolet` or `gmc`. Assign the result to `not_chevrolet_gmc`.

In [7]:
## YOUR SOLUTION HERE ##
is_chev = vehicles['manufacturer'] == 'chevrolet'
is_gmc = vehicles['manufacturer'] == 'gmc'
chev_gmc = is_chev | is_gmc


not_chevrolet_gmc = ~chev_gmc
not_chevrolet_gmc = vehicles[not_chevrolet_gmc]

# show output
not_chevrolet_gmc.head()

,id,model,year,transmission,manufacturer,vehicle_type,fuel,fuel_configuration,best_mpge
0,12988,amg e53 4matic+ (convertible),2022,auto,mercedes-benz,sedan/wagon,hybrid electric,hybrid electric,28.0
4,13089,sf90 spyder,2022,auto,ferrari,sedan/wagon,plug-in hybrid electric,hybrid electric,19.0
6,12989,amg gle 53 4matic+ (coupe),2022,auto,mercedes-benz,suv,hybrid electric,hybrid electric,21.0
7,12875,avalon hybrid,2022,auto,toyota,sedan/wagon,hybrid electric,hybrid electric,43.0
9,12864,x6 xdrive40i,2022,auto,bmw,suv,hybrid electric,hybrid electric,25.0