In [11]:
import pandas as pd
parks = pd.read_csv('nationalparks.csv')
parks.head()

,ParkTitle,City,State,ParkType,Area,AreaValues,Visitors2021
0,Great Smoky Mountains National Park,Gatlinburg,TN,National park,816.3 sqmi,816.3,14161548
1,Zion National Park,Springdale,UT,National park,229.1 sqmi,229.1,5039835
2,Yellowstone National Park,Jackson,WY,National park,3468.4 sqmi,3468.4,4860242
3,Grand Canyon National Park,Grand Canyon Village,AZ,National park,1902.0 sqmi,1902.0,4532677
4,Rocky Mountain National Park,Estes Park,CO,National park,414.8 sqmi,414.8,4434848

1. Display information about all the columns in this dataset.

In [12]:
parks.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ParkTitle     72 non-null     object
 1   City          72 non-null     object
 2   State         72 non-null     object
 3   ParkType      72 non-null     object
 4   Area          72 non-null     object
 5   AreaValues    72 non-null     float64
 6   Visitors2021  72 non-null     int64
dtypes: float64(1), int64(1), object(5)
memory usage: 4.1+ KB

2. The only information in `Area` that isn't in `AreaValues` are the units. Rename `AreaValues` to `Area_SqMi`.

In [13]:
mapper = {'AreaValues': 'Area_SqMi'}
parks = parks.rename(mapper = mapper, axis = 1)
parks

,ParkTitle,City,State,ParkType,Area,Area_SqMi,Visitors2021
0,Great Smoky Mountains National Park,Gatlinburg,TN,National park,816.3 sqmi,816.3,14161548
1,Zion National Park,Springdale,UT,National park,229.1 sqmi,229.1,5039835
2,Yellowstone National Park,Jackson,WY,National park,3468.4 sqmi,3468.4,4860242
3,Grand Canyon National Park,Grand Canyon Village,AZ,National park,1902.0 sqmi,1902.0,4532677
4,Rocky Mountain National Park,Estes Park,CO,National park,414.8 sqmi,414.8,4434848
...,...,...,...,...,...,...,...
67,Noatak National Preserve,Kotzebue,AK,National preserve,10265.5 sqmi,10265.5,12891
68,Kobuk Valley National Park,Kotzebue,AK,National park,2735.5 sqmi,2735.5,11540
69,Gates Of The Arctic National Park & Preserve,Bettles,AK,National park & preserve,13238.3 sqmi,13238.3,7362
70,Bering Land Bridge National Preserve,Nome,AK,National preserve,4214.7 sqmi,4214.7,2642
71,Yukon-Charley Rivers National Preserve,Fairbanks,AK,National preserve,3946.1 sqmi,3946.1,629

3. With the units in the title of `Area_SqMi` now, we can safely drop `Area`

In [14]:
parks = parks.drop('Area', axis = 1)
parks

,ParkTitle,City,State,ParkType,Area_SqMi,Visitors2021
0,Great Smoky Mountains National Park,Gatlinburg,TN,National park,816.3,14161548
1,Zion National Park,Springdale,UT,National park,229.1,5039835
2,Yellowstone National Park,Jackson,WY,National park,3468.4,4860242
3,Grand Canyon National Park,Grand Canyon Village,AZ,National park,1902.0,4532677
4,Rocky Mountain National Park,Estes Park,CO,National park,414.8,4434848
...,...,...,...,...,...,...
67,Noatak National Preserve,Kotzebue,AK,National preserve,10265.5,12891
68,Kobuk Valley National Park,Kotzebue,AK,National park,2735.5,11540
69,Gates Of The Arctic National Park & Preserve,Bettles,AK,National park & preserve,13238.3,7362
70,Bering Land Bridge National Preserve,Nome,AK,National preserve,4214.7,2642
71,Yukon-Charley Rivers National Preserve,Fairbanks,AK,National preserve,3946.1,629

4. Let's convert the column `Area_SqMi` from squared miles units to squared kilometers and assign it to a new column `Area_SqKm`. We'll use the sqmi to sqkm ratio $ 1:2.59 $ (that is, multiply the squared miles by 2.59).

In [15]:
parks['Area_SqKm'] = parks['Area_SqMi']*2.59
parks

,ParkTitle,City,State,ParkType,Area_SqMi,Visitors2021,Area_SqKm
0,Great Smoky Mountains National Park,Gatlinburg,TN,National park,816.3,14161548,2114.217
1,Zion National Park,Springdale,UT,National park,229.1,5039835,593.369
2,Yellowstone National Park,Jackson,WY,National park,3468.4,4860242,8983.156
3,Grand Canyon National Park,Grand Canyon Village,AZ,National park,1902.0,4532677,4926.180
4,Rocky Mountain National Park,Estes Park,CO,National park,414.8,4434848,1074.332
...,...,...,...,...,...,...,...
67,Noatak National Preserve,Kotzebue,AK,National preserve,10265.5,12891,26587.645
68,Kobuk Valley National Park,Kotzebue,AK,National park,2735.5,11540,7084.945
69,Gates Of The Arctic National Park & Preserve,Bettles,AK,National park & preserve,13238.3,7362,34287.197
70,Bering Land Bridge National Preserve,Nome,AK,National preserve,4214.7,2642,10916.073
71,Yukon-Charley Rivers National Preserve,Fairbanks,AK,National preserve,3946.1,629,10220.399

5. Calculate average daily visits in 2021 by dividing `Visitors2021` by `365`. Try rounding the result to a smaller number of decimals as well!

In [20]:
parks['Avg_daily_visit2021'] = (parks['Visitors2021']/365).round(2)

In [21]:
parks

,ParkTitle,City,State,ParkType,Area_SqMi,Visitors2021,Area_SqKm,Avg_daily_visit2021
0,Great Smoky Mountains National Park,Gatlinburg,TN,National park,816.3,14161548,2114.217,38798.76
1,Zion National Park,Springdale,UT,National park,229.1,5039835,593.369,13807.77
2,Yellowstone National Park,Jackson,WY,National park,3468.4,4860242,8983.156,13315.73
3,Grand Canyon National Park,Grand Canyon Village,AZ,National park,1902.0,4532677,4926.180,12418.29
4,Rocky Mountain National Park,Estes Park,CO,National park,414.8,4434848,1074.332,12150.27
...,...,...,...,...,...,...,...,...
67,Noatak National Preserve,Kotzebue,AK,National preserve,10265.5,12891,26587.645,35.32
68,Kobuk Valley National Park,Kotzebue,AK,National park,2735.5,11540,7084.945,31.62
69,Gates Of The Arctic National Park & Preserve,Bettles,AK,National park & preserve,13238.3,7362,34287.197,20.17
70,Bering Land Bridge National Preserve,Nome,AK,National preserve,4214.7,2642,10916.073,7.24
71,Yukon-Charley Rivers National Preserve,Fairbanks,AK,National preserve,3946.1,629,10220.399,1.72

6. The `ParkType` column should be categorical, but is currently `object`. Convert this column to `category` type.

In [22]:
parks['ParkType'] = parks['ParkType'].astype('category')

7. Use `.str.cat()` to create an information statement about each park: `ParkTitle is located in State`. Hint: use ` is located in ` as the argument for `sep`.

In [27]:
parks['Title_combined'] = parks['ParkTitle'].str.cat(parks['State'],
                                                     sep = ' is located in '
                                          )

In [28]:
parks['Title_combined']

0     Great Smoky Mountains National Park is located...
1                   Zion National Park is located in UT
2            Yellowstone National Park is located in WY
3           Grand Canyon National Park is located in AZ
4         Rocky Mountain National Park is located in CO
                            ...
67            Noatak National Preserve is located in AK
68          Kobuk Valley National Park is located in AK
69    Gates Of The Arctic National Park & Preserve i...
70    Bering Land Bridge National Preserve is locate...
71    Yukon-Charley Rivers National Preserve is loca...
Name: Title_combined, Length: 72, dtype: object