<details><summary style="display:list-item; font-size:16px; color:blue;">Jupyter Help</summary>
    
Having trouble testing your work? Double-check that you have followed the steps below to write, run, save, and test your code!
    
[Click here for a walkthrough GIF of the steps below](https://static-assets.codecademy.com/Courses/ds-python/jupyter-help.gif)

Run all initial cells to import libraries and datasets. Then follow these steps for each question:
    
1. Add your solution to the cell with `## YOUR SOLUTION HERE ## `.
2. Run the cell by selecting the `Run` button or the `Shift`+`Enter` keys.
3. Save your work by selecting the `Save` button, the `command`+`s` keys (Mac), or `control`+`s` keys (Windows).
4. Select the `Test Work` button at the bottom left to test your work.

![Screenshot of the buttons at the top of a Jupyter Notebook. The Run and Save buttons are highlighted](https://static-assets.codecademy.com/Paths/ds-python/jupyter-buttons.png)

Setup

In [1]:
import pandas as pd
vehicles = pd.read_csv('vehicles.csv')
vehicles.head()

,id,model,year,transmission,manufacturer,vehicle_type,fuel,fuel_configuration,best_mpge
0,12988,amg e53 4matic+ (convertible),2022,auto,mercedes-benz,sedan/wagon,hybrid electric,hybrid electric,28.0
1,689,avalanche ffv,2007,auto,chevrolet,pickup,ethanol (e85),flexible fuel,21.0
2,950,impala,2010,auto,chevrolet,sedan/wagon,ethanol (e85),flexible fuel,29.0
3,250,yukon xl ffv,2004,auto,gmc,suv,ethanol (e85),flexible fuel,18.0
4,13089,sf90 spyder,2022,auto,ferrari,sedan/wagon,plug-in hybrid electric,hybrid electric,19.0

1. Complete the code to select the first four rows and first five columns.

In [2]:
## YOUR SOLUTION HERE ##
sliced = vehicles.iloc[0:4,0:5]

# show output
sliced

      id                          model  year transmission   manufacturer
0  12988  amg e53 4matic+ (convertible)  2022         auto  mercedes-benz
1    689                  avalanche ffv  2007         auto      chevrolet
2    950                         impala  2010         auto      chevrolet
3    250                   yukon xl ffv  2004         auto            gmc

2. Complete the code to select the `chevrolet` rows in the setup cell output along with the `vehicle_type`, `fuel`, and `fuel_configuration` columns.

In [4]:
## YOUR SOLUTION HERE ##
chevy = vehicles.loc[1:2,'vehicle_type':'fuel_configuration']

# show output
chevy

  vehicle_type           fuel fuel_configuration
1       pickup  ethanol (e85)      flexible fuel
2  sedan/wagon  ethanol (e85)      flexible fuel

3. Complete the code to select all rows up to and including the 20th row, and all columns from `year` through to the end.

In [6]:
## YOUR SOLUTION HERE ##
large_slice = vehicles.loc[:19,'year':]

# show output
large_slice

,year,transmission,manufacturer,vehicle_type,fuel,fuel_configuration,best_mpge
0,2022,auto,mercedes-benz,sedan/wagon,hybrid electric,hybrid electric,28.0
1,2007,auto,chevrolet,pickup,ethanol (e85),flexible fuel,21.0
2,2010,auto,chevrolet,sedan/wagon,ethanol (e85),flexible fuel,29.0
3,2004,auto,gmc,suv,ethanol (e85),flexible fuel,18.0
4,2022,auto,ferrari,sedan/wagon,plug-in hybrid electric,hybrid electric,19.0
5,2020,auto,chevrolet,pickup,ethanol (e85),flexible fuel,18.0
6,2022,auto,mercedes-benz,suv,hybrid electric,hybrid electric,21.0
7,2022,auto,toyota,sedan/wagon,hybrid electric,hybrid electric,43.0
8,2013,auto,gmc,pickup,ethanol (e85),flexible fuel,18.0
9,2022,auto,bmw,suv,hybrid electric,hybrid electric,25.0
10,2013,unknown,smart,sedan/wagon,electric,dedicated,112.0
11,2013,auto,jeep,suv,ethanol (e85),flexible fuel,23.0
12,1998,auto,ford,van,cng - compressed natural gas,dual/bi-fueled,17.0
13,2012,auto,chevrolet,sedan/wagon,ethanol (e85),flexible fuel,30.0
14,2021,auto,audi,sedan/wagon,hybrid electric,hybrid electric,31.0
15,2014,auto,jaguar,sedan/wagon,ethanol (e85),flexible fuel,27.0
16,2018,auto,kia,sedan/wagon,plug-in hybrid electric,hybrid electric,103.0
17,2019,auto,chrysler,sedan/wagon,ethanol (e85),flexible fuel,27.0
18,2007,auto,gmc,pickup,hybrid electric,hybrid electric,21.0
19,2019,auto,chevrolet,sedan/wagon,biodiesel (b20),dedicated,48.0